name: SMPPositionSaver
version: 1.0.0
main: fr.smp.smpositionsaver.SMPPositionSaver
api-version: "1.21"
api: spigot
author: Eminium Games
description: Plugin to save and restore player positions in SMP worlds
website: https://github.com/Eminium-Games/SMPsystm
commands:
  smp:
    description: Teleports the player to the SMP coordinates defined in the configuration.
    usage: /smp [reload]
permissions:
  smppositionsaver.use:
    description: Allows using the position saving system
    default: true
  smp.reload:
    description: Allows reloading the configuration via /smp reload
    default: op
depend: []
softdepend: []
