name: SMPPositionSaver
version: '1.0.0'
main: fr.smp.smpositionsaver.SMPPositionSaver
api-version: 1.21
author: SMP Team
description: Plugin pour sauvegarder et restaurer les positions des joueurs dans les mondes SMP
commands: []
permissions:
  smppositionsaver.use:
    description: Permet d'utiliser le système de sauvegarde de position
    default: true
