name: SMPPositionSaver
version: 1.0.0
main: fr.smp.smpositionsaver.SMPPositionSaver
api-version: "1.21"
api: spigot
author: Eminium Games
description: Plugin pour sauvegarder et restaurer les positions des joueurs dans les mondes SMP
website: https://github.com/Eminium-Games/SMPsystm
commands: {}
permissions:
  smppositionsaver.use:
    description: Permet d'utiliser le système de sauvegarde de position
    default: true
depend: []
softdepend: []
